---
  Octavia.create_and_delete_pools:
    -
      args:
        pool_create_args:
          protocol: "HTTP"
          lb_algorithm: "ROUND_ROBIN"
        load_balancer_create_args: {}
      runner:
        type: "constant"
        times: 5
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2
        roles:
        - load-balancer_member
        network: {}
      sla:
        failure_rate:
          max: 0
